scan_filter_chain:
  - name: scan_filter_0
    type: laser_filters/LaserScanBoxFilter
    params:
      box_frame: "$(arg robot_name)/base_link"
      min_x: -0.07
      max_x: 0.07
      min_y: -0.07
      max_y: 0.07
      min_z: -1.0
      max_z: 1.0
